packageExtensions:
  freyr@0.1.0:
    dependencies:
      "@gatsbyjs/reach-router": ^1.3.6
      "@mikaelkristiansson/domready": ^1.0.11
      anser: ^2.0.1
      css.escape: ^1.5.1
      event-source-polyfill: ^1.0.22
      gatsby-legacy-polyfills: ^1.0.0
      gatsby-link: ^3.0.1
      gatsby-react-router-scroll: ^4.0.1
      lodash: ^4.17.21
      mitt: ^2.1.0
      platform: ^1.3.6
      prop-types: ^15.7.2
      query-string: ^6.14.1
      shallow-compare: ^1.2.2
      stack-trace: ^0.0.10
  gatsby-plugin-image@*:
    dependencies:
      "@babel/template": "*"
  vor@0.1.0:
    dependencies:
      "@gatsbyjs/reach-router": ^1.3.6
      "@mikaelkristiansson/domready": ^1.0.11
      anser: ^2.0.1
      css.escape: ^1.5.1
      event-source-polyfill: ^1.0.22
      gatsby-legacy-polyfills: ^1.0.0
      gatsby-link: ^3.0.1
      gatsby-react-router-scroll: ^4.0.1
      lodash: ^4.17.21
      mitt: ^2.1.0
      platform: ^1.3.6
      prop-types: ^15.7.2
      query-string: ^6.14.1
      shallow-compare: ^1.2.2
      stack-trace: ^0.0.10

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
