packageExtensions:
  "gatsby-plugin-image@*":
    dependencies:
      "@babel/template": "*"
#  "@auth0/nextjs-auth0@*":
#    dependencies:
#      tslib: "*"
#  "@cypress/webpack-preprocessor@*":
#    dependencies:
#      typescript: ^4.0.0
#  "@next/react-dev-overlay@*":
#    dependencies:
#      preact: ^10.5.5
#  "@types/minio@*":
#    dependencies:
#      "@types/events": "*"
#  "@types/webpack@*":
#    dependencies:
#      anymatch: "*"
#      tapable: "*"
#      webpack-sources: "*"
#  debug@*:
#    dependencies:
#      supports-color: "*"
#  eslint-plugin-import@*:
#    dependencies:
#      typescript: ^4.0.0
#  eslint-plugin-prettier@*:
#    dependencies:
#      eslint-config-prettier: "*"
#  next@*:
#    dependencies:
#      "@types/prop-types": "*"
#      "@types/webpack": "*"
#      esprima: "*"
#      preact: "*"
#  preact@*:
#    dependencies:
#      preact-render-to-string: ^5.1.10
#  react-query@*:
#    dependencies:
#      preact: ^10.5.5
#  "next-plugin-preact@*":
#    peerDependencies:
#      next: "^10.0.7"
#  "@prefresh/webpack@*":
#    peerDependencies:
#      next: "^10.0.7"
#  # this is a temporary fix for gatsby v3 lacking better  deps declaration, see gatsby#30114
  "freyr@0.1.0":
    dependencies:
      "@gatsbyjs/reach-router": "^1.3.6"
      "@mikaelkristiansson/domready": "^1.0.11"
      "gatsby-legacy-polyfills": "^1.0.0"
      "gatsby-link": "^3.0.1"
      "gatsby-react-router-scroll": "^4.0.1"
      "lodash": "^4.17.21"
      "mitt": "^2.1.0"
      "prop-types": "^15.7.2"
      "shallow-compare": "^1.2.2"
      "query-string": "^6.14.1"
      "stack-trace": "^0.0.10"
      "platform": "^1.3.6"
      "anser": "^2.0.1"
      "css.escape": "^1.5.1"
      "event-source-polyfill": "^1.0.22"
  "vor@0.1.0":
    dependencies:
      "@gatsbyjs/reach-router": "^1.3.6"
      "@mikaelkristiansson/domready": "^1.0.11"
      "gatsby-legacy-polyfills": "^1.0.0"
      "gatsby-link": "^3.0.1"
      "gatsby-react-router-scroll": "^4.0.1"
      "lodash": "^4.17.21"
      "mitt": "^2.1.0"
      "prop-types": "^15.7.2"
      "shallow-compare": "^1.2.2"
      "query-string": "^6.14.1"
      "stack-trace": "^0.0.10"
      "platform": "^1.3.6"
      "anser": "^2.0.1"
      "css.escape": "^1.5.1"
      "event-source-polyfill": "^1.0.22"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
