packageExtensions:
  "@auth0/nextjs-auth0@*":
    dependencies:
      tslib: "*"
  "@cypress/webpack-preprocessor@*":
    dependencies:
      typescript: ^4.0.0
  "@next/react-dev-overlay@*":
    dependencies:
      preact: ^10.5.5
  "@types/minio@*":
    dependencies:
      "@types/events": "*"
  "@types/webpack@*":
    dependencies:
      anymatch: "*"
      tapable: "*"
      webpack-sources: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-plugin-import@*:
    dependencies:
      typescript: ^4.0.0
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
  next@*:
    dependencies:
      "@types/prop-types": "*"
      "@types/webpack": "*"
      esprima: "*"
      preact: "*"
  optimized-images-loader@*:
    dependencies:
      "@babel/preset-env": "*"
      "@babel/preset-react": "*"
      "@svgr/core": "*"
  preact@*:
    dependencies:
      preact-render-to-string: ^5.1.10
  react-optimized-image@*:
    dependencies:
      preact: ^10.5.5
  react-query-devtools@*:
    dependencies:
      preact: ^10.5.5
  react-query@*:
    dependencies:
      preact: ^10.5.5

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.0.cjs
