plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.3.3.cjs

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  # Fix gaia deps
  "@next/react-dev-overlay@*":
    dependencies:
      preact: "^10.5.5"
  react-query@*:
    dependencies:
      preact: "^10.5.5"
  react-query-devtools@*:
    dependencies:
      preact: "^10.5.5"
  "@auth0/nextjs-auth0@*":
    dependencies:
      tslib: "*"
  react-optimized-image@*:
    dependencies:
      preact: "^10.5.5"
  optimized-images-loader@*:
    dependencies:
      "@svgr/core": "*"
      "@babel/preset-react": "*"
      "@babel/preset-env": "*"
  "@types/minio@*":
    dependencies:
      "@types/events": "*"
  "@types/webpack@*":
    dependencies:
      tapable: "*"
      anymatch: "*"
      webpack-sources: "*"
  next@*:
    dependencies:
      "@types/webpack": "*"
      preact: "*"
      "@types/prop-types": "*"
      esprima: "*"
  preact@*:
    dependencies:
      preact-render-to-string: "^5.1.10"
  eslint-plugin-import@*:
    dependencies:
      typescript: "^4.0.0"
  "@cypress/webpack-preprocessor@*":
    dependencies:
      typescript: "^4.0.0"
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
