## Docker Compose for development
version: "3"
services:
  vor_app:
    image: chrsep/go-devtools:latest
    container_name: vor_app
    working_dir: /src/vor
    environment:
      # go-devtools docker specific env
      SRC_ENTRYPOINT: /src/vor/pkg/*.go
    volumes:
      - .:/src/vor
    ports:
      - "40000:40000"
      - "8080:8080"
    depends_on:
      - db
    # Might not be necessary for all projects, but these
    # fixes delve crash on circleci
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - "SYS_PTRACE"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dev.dockerfile
    restart: unless-stopped
    depends_on:
      - vor_app
    ports:
      - "8000:80"

  db:
    build:
      context: ./docker/postgres/
      dockerfile: dev.dockerfile
    container_name: vor-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
       - vor:/var/lib/postgresql/data

volumes:
   vor:
