version: 2.1
jobs:
  frontend_build:
    docker:
      - image: node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - build-v3-{{ checksum "yarn.lock" }}
      - run: |
          yarn install --frozen-lockfile
      - run: |
          mv ./apps/vor/frontend/.babelrc.ci.json ./apps/vor/frontend/.babelrc
      - run: |
          yarn workspace vor run build:ci
      - persist_to_workspace:
          root: ../
          paths:
            - repo/node_modules
            - repo/apps/vor/frontend/.cache
            - repo/apps/vor/frontend/public
            - .cache/Cypress
      - save_cache:
          when: always
          name: Save Yarn Package Cache
          key: build-v3-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
            - ./node_modules
      - store_artifacts:
          path: ./vor/frontend/public

  e2e:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    environment:
      NODE_ENV: "staging"
    parallelism: 2
    steps:
      - checkout
      - run: cp .env.example .env
      - run:
          command: docker-compose up
          background: true
      - attach_workspace:
          at: ../
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          nvm install v12
          node -v
          nvm alias default v12
      - run: npm install -g yarn
      - run: |
          yarn workspace e2e run cy:ci
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ~/repo/apps/vor/frontend/cypress/videos
          destination: cypress-videos
      - store_artifacts:
          path: ~/repo/apps/vor/frontend/cypress/screenshots
          destination: cypress-screenshots

  backend_unit:
    docker:
      - image: golang:1.13
      - image: circleci/postgres:11
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: defaultdb
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: |
          cd apps/vor/
          mkdir test_result
          mkdir test_result/go
          go get gotest.tools/gotestsum
          PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
          gotestsum --junitfile test_result/go/gotestsum-report.xml -- $PACKAGE_NAMES -v -coverprofile=coverage.txt -covermode=atomic -coverpkg $(go list ./... | grep -v "test" | paste -s -d",")
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: apps/vor/test_result

  frontend_unit:
    docker:
      - image: node:12
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ../
      - run: |
          yarn workspace vor test -w 1
      - run: bash <(curl -s https://codecov.io/bash)

  frontend_lint:
    docker:
      - image: node:12
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ../
      - run: |
          yarn workspace vor run lint

  frontend_typecheck:
    docker:
      - image: node:12
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ../
      - run: |
          yarn workspace vor run typecheck

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          sudo apt update && sudo apt install docker-ce
          nvm install v12
          node -v
          nvm alias default v12
      - run: |
          git config --global user.email "chrsep@protonmail.com"
          git config --global user.name "Chrisando Pramudhita"
      - run: |
          npm install -g standard-version
          standard-version -m 'chore(release): %s [skip ci]' --releaseCommitMessageFormat --no-verify
      - run: |
          git push --follow-tags origin master
      - run: |
          echo "GA_CLIENT_EMAIL=$GA_CLIENT_EMAIL" >> .env
          echo "GA_PRIVATE_KEY=$GA_PRIVATE_KEY" >> .env
      - run: |
          VERSION=$(cat VERSION)
          DOCKER_BUILDKIT=1 docker build -f ./docker/vor/prod.dockerfile  -t "chrsep/vor:$VERSION" . --secret id=env,src=.env
      - run: |
          VERSION=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
          docker push chrsep/vor:$VERSION
      - run: |
          npm install -g @sentry/cli
      - run: |
          VERSION=$(cat VERSION)
          sentry-cli releases -p frontend new $VERSION
          sentry-cli releases -p frontend set-commits --auto $VERSION
          sentry-cli releases -p frontend finalize $VERSION
      - run: |
          VERSION=$(sentry-cli releases propose-version)
          sentry-cli releases -p backend new $VERSION
          sentry-cli releases -p backend set-commits --auto $VERSION
          sentry-cli releases -p backend finalize $VERSION

orbs:
  go: circleci/go@1.1.1

workflows:
  vor:
    jobs:
      - frontend_build
      - backend_unit
      - frontend_lint:
          requires:
            - frontend_build
      - frontend_typecheck:
          requires:
            - frontend_build
      - frontend_unit:
          requires:
            - frontend_build
      - e2e:
          requires:
            - frontend_build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - e2e
            - backend_unit
            - frontend_unit
            - frontend_lint
            - frontend_typecheck
