# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on: [ push ]

jobs:
  build-vor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache deps and gatsby
        uses: actions/cache@v2
        id: cache-deps-and-gatsby
        env:
          cache-name: cache-build-vor
        with:
          path: |
            .yarn
            .pnp.js
            apps/vor/frontend/public
            apps/vor/frontend/.cache
          key: v1-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn workspaces focus vor --production
      - run: yarn workspace vor run build

  build-gaia:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache nextjs and deps
        id: cache-deps
        uses: actions/cache@v2
        env:
          cache-name: cache-build-gaia
        with:
          path: |
            .yarn
            .pnp.js
            apps/gaia/.next
          key: v1-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn workspaces focus gaia --production
      - run: yarn workspace gaia run build

