# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build-vor-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache deps and gatsby
        uses: actions/cache@v2
        id: cache-deps-and-gatsby
        env:
          cache-name: cache-build-vor
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
            .yarn/build-state.yml
            .pnp.js
            apps/vor/frontend/public
            apps/vor/frontend/.cache
          key: v3-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.pnp.js') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Cache translations
        uses: actions/cache@v2
        id: cache-translations
        env:
          cache-name: cache-vor-translations
        with:
          path: apps/vor/frontend/i18n
          key: v1-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('apps/vor/frontend/i18n/**/messages.po') }} }}
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        if: steps.cache-deps-and-gatsby.outputs.cache-hit != 'true'
        run: yarn workspaces focus vor --production
      - name: Compile translations
        if: steps.cache-translations.outputs.cache-hit != 'true'
        run: yarn workspace vor run i18n:compile
      - name: Gatsby build
        run: yarn workspace vor run build:ci
      - uses: actions/upload-artifact@v2
        with:
          name: vor
          path: apps/vor/frontend/public

  build-gaia:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache nextjs and deps
        id: cache-deps
        uses: actions/cache@v2
        env:
          cache-name: cache-build-gaia
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
            .yarn/build-state.yml
            .pnp.js
            apps/gaia/.next
          key: v3-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.pnp.js') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn workspaces focus gaia --production
      - run: yarn workspace gaia run build
      - uses: actions/upload-artifact@v2
        with:
          name: gaia
          path: apps/gaia/.next

  test-vor-backend:
    runs-on: ubuntu-latest

    services:
      minio:
        image: chrsep/minio:latest
        env:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
          MINIO_HTTP_TRACE: "/dev/stdout"
        ports:
          - 9000:9000
      postgres:
        image: obserfy/postgres-dev:latest
        env:
          POSTGRES_MULTIPLE_DATABASES: defaultdb,defaultdb_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
      MINIO_ENDPOINT: localhost:9000
      MINIO_BUCKET_NAME: media
      MINIO_BUCKET_LOCATION: us-east-1
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v2
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v2
        env:
          cache-name: cache-vor-backend-deps
        with:
          path: |
            apps/vor/vendor
          key: v2-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.mod') }}
      - name: Use Go 15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.3
      - run: cd apps/vor/ && go get gotest.tools/gotestsum
      - run: cd apps/vor/ && go mod vendor
      - run: |
          cd apps/vor/
          mkdir test_result
          mkdir test_result/go
          PACKAGE_NAMES=$(go list ./...)
          gotestsum --junitfile test_result/go/gotestsum-report.xml -- $PACKAGE_NAMES -v -coverprofile=coverage.txt -covermode=atomic -coverpkg $(go list ./... | grep -v "test" | paste -s -d",")

  vor-snapshot-test:
    runs-on: ubuntu-latest

    needs:
      - build-vor-frontend

    steps:
      - uses: actions/checkout@v2
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v2
        env:
          cache-name: cache-vor-snapshot-test
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
            .yarn/build-state.yml
            .pnp.js
          key: v2-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.pnp.js') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn workspaces focus vor
      - uses: actions/download-artifact@v2
        with:
          name: vor
          path: apps/vor/frontend/public
      - run: yarn workspace vor run test

  e2e-parallel:
    if:  ${{ !contains('renovate', github.ref) }}
    needs:
      - build-gaia
      - build-vor-frontend
    runs-on: ubuntu-latest

    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      CYPRESS_VOR_HOST: https://localhost:8000
      CYPRESS_GAIA_HOST: http://localhost:3000
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [ 1, 2, 3 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: vor
          path: apps/vor/frontend/public
      - uses: actions/download-artifact@v2
        with:
          name: gaia
          path: apps/gaia/.next
      - run: touch .env.local # stop docker-compose from complaining about missing file.
      - run: docker-compose up -d &
      - name: Cache e2e deps
        id: cache-deps
        uses: pat-s/always-upload-cache@v2.1.3
        env:
          cache-name: cache-build-e2e
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
            .yarn/build-state.yml
            .pnp.js
            ~/.cache/Cypress
          key: v3-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.pnp.js') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn workspaces focus e2e gaia
      - run: yarn workspace gaia run start &
        env:
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      - name: Cypress parallel run
        uses: cypress-io/github-action@v2
        with:
          command: yarn workspace e2e run cy:run --record --parallel --config baseUrl=https://localhost:8000
          record: true
          parallel: true
          group: 'E2E'
          wait-on: 'https://localhost:8000/login, http://localhost:3000'
          install: false
          working-directory: ./apps/e2e
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # secret envs
          CYPRESS_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          CYPRESS_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          CYPRESS_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          CYPRESS_GAIA_USERNAME: ${{ secrets.CYPRESS_GAIA_USERNAME }}
          CYPRESS_GAIA_PASSWORD: ${{ secrets.CYPRESS_GAIA_PASSWORD }}
          CYPRESS_VOR_HOST: 'https://localhost:8000'
          CYPRESS_GAIA_HOST: 'http://localhost:3000'
