name: Deploy Docker Images

on: [ push ]
#on:
#  push:
#    tags:
#      - '*'

jobs:
  deploy-vor:
    runs-on: ubuntu-latest


    env:
      DOCKER_BUILDKIT: 1
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build docker image
        run: docker build -f ./docker/vor/prod.dockerfile  -t "obserfy/vor:latest"
#        run: docker build -f ./docker/vor/prod.dockerfile  -t "obserfy/vor:latest" .
#          docker build -f ./docker/vor/prod.dockerfile  -t "obserfy/vor:${{ steps.get_version.outputs.VERSION  }}" .
      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN"  --password-stdin

  deploy-gaia:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      NEXT_PUBLIC_GAIA_SEGMENT_KEY: ${{ secrets.NEXT_PUBLIC_GAIA_SEGMENT_KEY }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build docker image
        run: docker build --build-arg NEXT_PUBLIC_GAIA_SEGMENT_KEY -f ./docker/gaia/prod.dockerfile  -t "obserfy/gaia:latest"  .
#        run: docker build --build-arg NEXT_PUBLIC_GAIA_SEGMENT_KEY -f ./docker/gaia/prod.dockerfile  -t "obserfy/gaia:${{ steps.get_version.outputs.VERSION  }}"  .
      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN"  --password-stdin

