name: Release

on:
  push:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Commit files
        run: |
          git config --local user.email "gilfoyle@obserfy.com"
          git config --local user.name "Gilfoyle"
      - run: "npx standard-version -m 'chore(release): %s [skip ci]' --releaseCommitMessageFormat --no-verify"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}