# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Static Analysis

on: [push]

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache typecheck deps
        uses: actions/cache@v2
        id: cache-deps
        env:
          cache-name: cache-typecheck
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
            .yarn/build-state.yml
            .pnp.js
          key: v1-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.pnp.js') }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn
      - run: yarn workspaces foreach -p run typecheck

  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache lint deps
        uses: actions/cache@v2
        id: cache-deps
        env:
          cache-name: cache-lint
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
            .yarn/build-state.yml
            .pnp.js
          key: v1-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.pnp.js') }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn
      - run: yarn workspaces foreach -p run lint
